import { test, expect, management } from './fixtures.js';
test('CSV upload reports rejected rows, displays roster and confirms invitations', async ({ page, api }) => {
  api.authenticated = true;
  await page.goto(`/#${management}`);
  await page.getByLabel(/^Contact name/).fill('Roster Admin');
  await page.getByLabel(/^Contact email/).fill('roster@example.test');
  await page.getByRole('button', { name: 'Upload list', exact: true }).click();
  await expect(page.getByText('Choose a CSV file to upload.')).toBeVisible();
  expect(api.calls.some(c => c.path === '/institute-lists/upload/')).toBe(false);
  await page.locator('input[type="file"]').setInputFiles({ name: 'roster.csv', mimeType: 'text/csv', buffer: Buffer.from('full_name,email,field_of_study,degree_level,expected_graduation\nAda Student,ada@example.test,Computer Science,Bachelor,2027\nBad Row,invalid,Science,Bachelor,2027\n') });
  await page.getByRole('button', { name: 'Upload list', exact: true }).click();
  await expect(page.getByText('Upload complete', { exact: true })).toBeVisible();
  await expect(page.getByText('Invalid email', { exact: true })).toBeVisible();
  expect(api.calls.some(c => c.path.endsWith('/send-invites/'))).toBe(false);
  await page.getByRole('link', { name: 'View roster & send invites' }).click();
  await expect(page.getByText('Ada Student', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Send invites', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel' }).click();
  await expect(page.getByRole('dialog')).toBeHidden();
  expect(api.calls.some(c => c.path.endsWith('/send-invites/'))).toBe(false);
  await page.getByRole('button', { name: 'Send invites', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Send invites', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeHidden();
  await expect(page.getByRole('button', { name: 'Send invites', exact: true })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Resend to invited', exact: true })).toBeEnabled();
  expect(api.calls.filter(c => c.path.endsWith('/send-invites/'))).toHaveLength(1);
  await page.getByRole('button', { name: 'Resend to invited', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Resend to all invited' }).click();
  await expect(page.getByRole('dialog')).toBeHidden();
  await expect.poll(() => api.calls.filter(c => c.path.endsWith('/send-invites/')).length).toBe(2);
  expect(api.calls.filter(c => c.path.endsWith('/send-invites/'))[1].body).toEqual({ resend: true });
});
