import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import { AuthSession } from '../../models/onboarding';
import { notificationInboxRequest } from '../../services/notifications';
import { colors, fonts } from '../../theme/tokens';

export type QueryNavigation = { id?: number; direction?: string; key: number };
type Query = {id:number; question:string; answer:string; status:string; direction:string; university_name:string; raised_by_agent:string; created_at:string; answered_at?:string};
type Result = {results:Query[]; pagination:{page:number; total:number; has_next:boolean}};
export function StudentQueriesPanel({session, selection}:{session?:AuthSession; selection?:QueryNavigation}) {
  const [direction,setDirection]=useState('student_to_university');
  const [focused,setFocused]=useState<number>();
  const [search,setSearch]=useState(''); const [term,setTerm]=useState('');
  const [page,setPage]=useState(1); const [data,setData]=useState<Result>();
  const [error,setError]=useState(''); const [expanded,setExpanded]=useState<number>();
  const [draft,setDraft]=useState<{id:number;answer:string;review:boolean}>();
  const [busy,setBusy]=useState(false); const generation=useRef(0);
  useEffect(()=>{if(selection){setFocused(selection.id);setDirection(selection.direction||'university_to_student');setPage(1);setTerm('');setSearch('');setExpanded(selection.id);}},[selection]);
  const load=useCallback(async()=>{
    if(!session)return; const id=++generation.current;
    try{const params=new URLSearchParams({direction,page:String(page),search:term});if(focused)params.set('query_id',String(focused));const next=await notificationInboxRequest<Result>(session,`/agent-queries/?${params}`);if(id===generation.current){setData(next);setError('');}}
    catch(e){if(id===generation.current)setError(e instanceof Error?e.message:'Unable to load queries.');}
  },[session,direction,page,term,focused]);
  useEffect(()=>{setData(undefined);load();const timer=setInterval(load,30000);return()=>{++generation.current;clearInterval(timer);};},[load]);
  const submit=async()=>{if(!session||!draft)return;setBusy(true);try{await notificationInboxRequest(session,`/agent-queries/${draft.id}/answer/`,{method:'POST',body:JSON.stringify({answer:draft.answer,confirmed:true,answer_scope:'private'})});setExpanded(draft.id);setDraft(undefined);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to send answer.');}finally{setBusy(false);}};
  const button=(label:string,onPress:()=>void,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.button,disabled&&{opacity:.4}]}><Text style={styles.buttonText}>{label}</Text></Pressable>;
  return <View style={styles.root}><Text style={styles.eyebrow}>YOUR AGENT'S CONVERSATIONS</Text><Text style={styles.title}>Queries</Text><Text style={styles.muted}>Questions your agent raises with universities, and information their agents request from you.</Text>
    <View style={styles.row}>{[['student_to_university','Raised by you'],['university_to_student','Raised by university']].map(([value,label])=><Pressable key={value} accessibilityRole="tab" accessibilityState={{selected:direction===value}} onPress={()=>{setDirection(value || "student_to_university");setFocused(undefined);setPage(1);setDraft(undefined);}} style={[styles.tab,direction===value&&styles.activeTab]}><Text style={[styles.tabText,direction===value&&styles.activeText]}>{label}</Text></Pressable>)}</View>
    <View style={styles.row}><TextInput accessibilityLabel="Search queries" placeholder="Search questions or universities" placeholderTextColor={colors.muted} value={search} onChangeText={setSearch} onSubmitEditing={()=>{setTerm(search.trim());setPage(1);}} style={styles.search}/><Pressable accessibilityRole="button" accessibilityLabel="Search" onPress={()=>{setTerm(search.trim());setPage(1);}} style={styles.searchButton}><MaterialIcons name="search" size={22} color={colors.text}/></Pressable></View>
    {focused?button('Show all queries',()=>{setFocused(undefined);setPage(1);}):null}
    {error?<View style={styles.error}><Text style={{color:'#a52c30'}}>{error}</Text>{button('Retry',load)}</View>:null}
    {!data&&!error?<ActivityIndicator color={colors.coral}/>:null}
    {data?.results.length===0?<View style={styles.empty}><MaterialIcons name="forum" size={32} color={colors.muted}/><Text style={styles.cardTitle}>No queries yet</Text><Text style={styles.muted}>Your agent’s questions will appear here. Try a different search if you’re looking for an older query.</Text></View>:null}
    {data?.results.map(item=><View key={item.id} style={[styles.card,{borderLeftColor:item.status==='answered'?'#39805a':'#c85a54'}]}>
      <View style={styles.between}><Text style={styles.university}>{item.university_name}</Text><Text style={[styles.badge,{color:item.status==='answered'?'#287446':'#aa3835',backgroundColor:item.status==='answered'?'#e9f4ec':'#fff0ee'}]}>{item.status==='answered'?'Answered':'Unanswered'}</Text></View>
      <Text style={styles.question}>{item.question}</Text><Text style={styles.small}>{item.raised_by_agent} · {new Date(item.created_at).toLocaleString()}</Text>
      {item.status==='answered'?<><Pressable accessibilityRole="button" accessibilityState={{expanded:expanded===item.id}} onPress={()=>setExpanded(expanded===item.id?undefined:item.id)} style={styles.answerToggle}><Text style={styles.link}>{expanded===item.id?'Hide answer':'View answer'}</Text><MaterialIcons name={expanded===item.id?'expand-less':'expand-more'} color={colors.coral} size={22}/></Pressable>{expanded===item.id?<View style={styles.answer}><Text style={styles.answerText}>{item.answer}</Text><Text style={styles.small}>{item.answered_at?new Date(item.answered_at).toLocaleString():''}</Text></View>:null}</>:item.direction==='university_to_student'?button('Answer query',()=>setDraft({id:item.id,answer:'',review:false})): <Text style={styles.muted}>Waiting for the university. We’ll notify you when they answer.</Text>}
      {draft?.id===item.id?<View style={styles.answer}><Text style={styles.cardTitle}>Your answer</Text><TextInput accessibilityLabel="Your answer" multiline maxLength={12000} editable={!draft.review&&!busy} value={draft.answer} onChangeText={answer=>setDraft({...draft,answer})} placeholder="Provide the requested information…" placeholderTextColor={colors.muted} style={styles.editor}/><Text style={styles.small}>Shared with {item.university_name} and saved as your answer. This does not replace your résumé or profile fields.</Text>{draft.review?<Text style={styles.link}>Confirm the answer above before sending.</Text>:null}<View style={styles.row}>{button(busy?'Sending…':draft.review?'Confirm and send':'Review answer',()=>draft.review?submit():setDraft({...draft,review:true}),busy||!draft.answer.trim())}{button(draft.review?'Edit':'Cancel',()=>draft.review?setDraft({...draft,review:false}):setDraft(undefined),busy)}</View></View>:null}
    </View>)}
    {data?<View style={styles.between}>{button('Previous',()=>setPage(page-1),page<=1)}<Text style={styles.small}>Page {page} · {data.pagination.total} queries</Text>{button('Next',()=>setPage(page+1),!data.pagination.has_next)}</View>:null}
  </View>;
}
const styles=StyleSheet.create({root:{gap:16,paddingBottom:28},eyebrow:{fontFamily:fonts.bodyMedium,fontSize:11,letterSpacing:1.5,color:colors.muted},title:{fontSize:30,fontFamily:fonts.bodyMedium,color:colors.text},muted:{fontFamily:fonts.body,fontSize:14,lineHeight:22,color:colors.textSoft},row:{flexDirection:'row',gap:8,alignItems:'center',flexWrap:'wrap'},between:{flexDirection:'row',gap:10,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap'},tab:{flex:1,minWidth:130,borderRadius:12,padding:13,backgroundColor:colors.panelInk,borderWidth:1,borderColor:colors.border},activeTab:{backgroundColor:colors.coral,borderColor:colors.coral},tabText:{textAlign:'center',fontFamily:fonts.bodyMedium,color:colors.textSoft,fontSize:13},activeText:{color:'#fff'},search:{flex:1,minWidth:140,borderWidth:1,borderColor:colors.border,borderRadius:12,padding:13,fontFamily:fonts.body,color:colors.text,backgroundColor:'#fff'},searchButton:{padding:12,borderRadius:12,backgroundColor:colors.panelInk},card:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderLeftWidth:4,borderRadius:16,padding:18,gap:13},university:{fontFamily:fonts.bodyMedium,color:colors.text,fontSize:14,flexShrink:1},question:{fontFamily:fonts.bodyMedium,fontSize:16,lineHeight:25,color:colors.text},small:{fontFamily:fonts.body,fontSize:11,lineHeight:18,color:colors.muted},badge:{fontSize:11,fontFamily:fonts.bodyMedium,paddingHorizontal:9,paddingVertical:5,borderRadius:12},button:{paddingHorizontal:14,paddingVertical:11,borderRadius:10,backgroundColor:colors.coral,alignSelf:'flex-start'},buttonText:{fontFamily:fonts.bodyMedium,fontSize:12,color:'#fff'},answerToggle:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},link:{fontFamily:fonts.bodyMedium,fontSize:13,color:colors.coral},answer:{gap:12,borderRadius:12,padding:14,backgroundColor:colors.panelInk},answerText:{fontFamily:fonts.body,fontSize:14,lineHeight:24,color:colors.text},editor:{minHeight:120,textAlignVertical:'top',borderWidth:1,borderColor:colors.border,borderRadius:10,padding:12,backgroundColor:'#fff',color:colors.text,fontFamily:fonts.body},empty:{padding:28,borderRadius:16,borderWidth:1,borderColor:colors.border,alignItems:'center',gap:12,backgroundColor:'#fff'},cardTitle:{fontFamily:fonts.bodyMedium,fontSize:15,color:colors.text},error:{padding:14,borderRadius:12,backgroundColor:'#fff0ee',gap:10}});
