import { StudentProfile } from './types';

export const sampleProfile: StudentProfile = {
  name: 'Kalyani Ghatol',
  email: 'ghatolkalyani2005@gmail.com',
  profile_image_url: null,
  country: '',
  institution: 'Shri Sant Gajanan Maharaj College of Engineering, Shegaon',
  major: 'Computer Science and Engineering',
  program: 'MS Computer Science',
  graduation_year: null,
  gpa: 8.8,
  gpa_scale: '10.0',
  gpa_text: '',
  gre_quant: null,
  gre_verbal: null,
  toefl: null,
  ielts: null,
  english_score_text: '',
  budget: null,
  budget_text: '',
  work_months: 7,
  github: '',
  linkedin_url: '',
  notes:
    'Profile from resume. Student is currently pursuing B.E. Graduation year, budget, target disciplines, standardized tests, research experience, and academic achievements should be collected.',
  source: 'resume',
  verified: false,
  skills: [
    'C',
    'Java',
    'JavaScript',
    'Python',
    'HTML',
    'CSS',
    'MERN Stack',
    'React.js',
    'Node.js',
    'Power BI',
    'Docker',
    'Kubernetes',
    'RESTful APIs',
    'OpenCV',
    'Postman',
  ],
  technical_skills: [
    'C',
    'Java',
    'JavaScript',
    'Python',
    'HTML',
    'CSS',
    'MERN Stack',
    'React.js',
    'Node.js',
    'Power Apps',
    'Power BI',
    'Power Automate',
    'Excel',
    'SharePoint',
    'Figma',
    'Canva',
    'Git/GitHub',
    'Docker',
    'Kubernetes',
    'RESTful APIs',
    'OpenCV',
    'Easy OCR',
    'Postman',
    'OOPS',
    'DBMS',
    'Data Structures and Algorithms',
  ],
  soft_skills: [],
  projects: [
    {
      title: 'SmartChat AI',
      description:
        'A full-stack project that answers user questions and displays a fallback message if no answer is found. Tested and validated API responses using Postman.',
      technologies: ['HTML', 'CSS', 'MERN Stack', 'Postman'],
    },
    {
      title: 'Offline OCR System',
      description:
        'Built an offline OCR tool using Easy OCR. Implemented OpenCV image preprocessing to enhance accuracy and managed local document processing.',
      technologies: ['Easy OCR', 'OpenCV', 'JavaScript'],
    },
    {
      title: 'Portfolio',
      description:
        'Developed a full-stack portfolio website to showcase projects, skills, and achievements with a responsive UI.',
      technologies: ['HTML', 'CSS', 'JavaScript', 'React.js', 'Node.js'],
    },
  ],
  research: 'None stated',
  research_interests: [],
  publications_count: 0,
  career_goals: [],
  academic_intelligence: {
    academic_score: 40,
    readiness: 'Needs Improvement',
    strengths: ['Outstanding academic performance'],
    weaknesses: ['GRE score not available.', 'TOEFL score unavailable.'],
    recommendations: [
      'Consider taking the GRE if the target universities recommend it.',
      'Complete an English proficiency test before applying.',
    ],
    evidence: ['GPA of 8.8 demonstrates excellent academic consistency.'],
  },
  technical_intelligence: {
    technical_score: 85,
    technical_level: 'Very Strong',
    skill_matrix: {
      'AI / Machine Learning': 2,
      'Web Development': 4,
      Databases: 0,
      Projects: 3,
      'Industry Experience Months': 7,
    },
    strengths: [
      'Basic AI / Machine Learning knowledge',
      'Strong Web Development skills',
      'Good practical project experience',
      'Strong industry experience',
    ],
    weaknesses: ['No database experience.'],
    recommendations: ['Create and maintain an active GitHub profile.'],
    evidence: [
      '2 AI-related technologies identified.',
      '4 Web Development technologies identified.',
      '3 projects completed.',
      '7.0 months of professional experience.',
    ],
  },
  research_intelligence: {
    research_score: 40,
    strengths: ['Research experience mentioned.'],
    weaknesses: ['Research interests are missing.'],
    recommendations: ['Try to publish or document research-based work.'],
  },
  behaviour_intelligence: {
    behaviour_score: 0,
    evidence_count: 0,
    summary: 'Behaviour analysis is based on stored conversation insights.',
  },
  overall_profile_score: 60,
  overall_profile: {
    overall_score: 60,
    profile_level: 'Moderate',
    recommendation: 'Strengthen the profile before applying to competitive universities.',
  },
  profile_completeness: {
    completed: 8,
    total: 12,
    percentage: 67,
    missing: ['gre_quant', 'toefl', 'budget', 'github'],
  },
  disciplines: [
    'Software Engineering',
    'Full Stack Web Development',
    'Data Engineering and Business Intelligence',
  ],
  gaps: [
    'budget',
    'target_disciplines',
    'graduation_year',
    'standardized_test_scores (GRE/TOEFL/IELTS)',
    'research_experience',
    'academic_awards_and_achievements',
  ],
  parser_status: 'success',
  parser_engine: 'claude',
  response_mode: 'detailed',
  work_experience_summary:
    'Project Intern at ASEA Brown Boveri (ABB) India Ltd.; Full Stack Development Intern at Apexa IQ; Full Stack Development Intern at One Smarter Inc.',
  student_id: 'kalyani_ghatol',
  created_at: '2026-07-09 11:09:32',
  updated_at: '2026-07-09 11:10:12',
};
